module.exports = {
  "By Example": "通过例子",
  "Consumption": "使用",
  "Deep Dive": "深入探讨",
  "Dos and Donts": "该做和不该做",
  "Introduction": "介绍",
  "Library Structures": "库结构",
  "Publishing": "发布",
  "Templates": "模板",
  "global-modifying-module": "全局修改模块",
  "global-plugin": "全局插件",
  "global": "全局",
  "module-class": "模块类",
  "module-function": "模块函数",
  "module-plugin": "模块插件",
  "module": "模块",
  "Classes": "类",
  "Functions": "函数",
  "Generics": "泛型",
  "Interfaces": "接口",
  "Literal Types": "字面量类型",
  "Unions and Intersections": "联合类型和交叉类型",
  "Basics": "基础",
  "Everyday Types": "常见类型",
  "Modules": "模块",
  "More on Functions": "函数进阶",
  "Narrowing": "类型缩小",
  "Object Types": "对象类型",
  "The Handbook": "手册",
  "Type Declarations": "类型声明",
  "Understanding Errors": "了解错误",
  "Conditional Types": "条件类型",
  "Indexed Access Types": "索引访问类型",
  "Keyof Type Operator": "Keyof 类型运算符",
  "Mapped Types": "映射类型",
  "Template Literal Types": "模板字面量类型",
  "Typeof Type Operator": "Typeof 类型运算符",
  "_Creating Types from Types": "从类型创建类型",
  "Advanced Types": "高级类型",
  "Declaration Merging": "声明合并",
  "Decorators": "装饰器",
  "ESM Support for Node": "Node 的 ESM 支持",
  "Enums": "枚举",
  "Iterators and Generators": "迭代器和生成器",
  "JSX": "JSX",
  "Mixins": "混合",
  "Module Resolution": "模块解析",
  "Namespaces and Modules": "命名空间和模块",
  "Namespaces": "命名空间",
  "Symbols": "符号",
  "Triple-Slash Directives": "三斜线指令",
  "Type Compatibility": "类型兼容性",
  "Type Inference": "类型推断",
  "Utility Types": "实用类型",
  "Variable Declarations": "变量声明",
  "exclude": "排除",
  "include": "包含",
  "Compiler Options in MSBuild": "MSBuild 中的编译器选项",
  "Compiler Options": "编译器选项",
  "Configuring Watch": "配置监视",
  "Integrating with Build Tools": "与构建工具集成",
  "Project References": "项目引用",
  "tsconfig": "tsconfig",
  "Top Level": "顶层",
  "buildOptions": "构建选项",
  "compilerOptions": "编译器选项",
  "typeAcquisition": "类型获取",
  "watchOptions": "监视选项",
  "ASP.NET Core": "ASP.NET Core",
  "Angular": "Angular",
  "Babel with TypeScript": "Babel 和 TypeScript",
  "DOM Manipulation": "DOM 操作",
  "Gulp": "Gulp",
  "Migrating from JavaScript": "从 JavaScript 迁移",
  "React": "React",
  "TypeScript Tooling in 5 minutes": "5分钟快速入门 TypeScript 工具链",
  "TS for Functional Programmers": "面向函数编程者的 TypeScript",
  "TS for JS Programmers": "面向 JavaScript 程序员的 TypeScript",
  "TS for OOPers": "面向面向对象编程者的 TypeScript",
  "TS for the New Programmer": "新手学 TypeScript",
  "Creating DTS files From JS": "从 JS 文件创建 DTS 文件",
  "Intro to JS with TS": "使用 TypeScript 介绍 JavaScript",
  "JSDoc Reference": "JSDoc 参考",
  "Type Checking JavaScript Files": "JavaScript 文件类型检查",
  "Conditional Types": "条件类型",
  "Indexed Access Types": "索引访问类型",
  "Keyof Type Operator": "Keyof 类型运算符",
  "Mapped Types": "映射类型",
  "Template Literal Types": "模板字面量类型",
  "Typeof Type Operator": "Typeof 类型运算符",
  "declaration-files": "声明文件",
  "templates": "模板",
  "handbook-v1": "手册 v1",
  "handbook-v2": "手册 v2",
  "Type Manipulation": "类型操作",
  "reference": "参考文献",
  "release-notes": "发布版本",
  "options": "选项",
  "typeAcquisition": "类型获取",
  "project-config": "项目配置",
  "sections": "章节列表",
  "tutorials": "辅助教程",
  "get-started": "快速入门",
  "javascript": "JavaScript",
}